# Generated by Django 5.0.4 on 2024-04-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('my_field', models.CharField(choices=[('stock', 'stock'), ('outstock', 'ouststock')], max_length=20)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
    ]
